// Code generated by mockery v2.23.4. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/Chystik/pass-man/internal/vault/card/entities"
	mock "github.com/stretchr/testify/mock"
)

// CardUsecases is an autogenerated mock type for the CardUsecases type
type CardUsecases struct {
	mock.Mock
}

type CardUsecases_Expecter struct {
	mock *mock.Mock
}

func (_m *CardUsecases) EXPECT() *CardUsecases_Expecter {
	return &CardUsecases_Expecter{mock: &_m.Mock}
}

// AddCard provides a mock function with given fields: ctx, userID, card
func (_m *CardUsecases) AddCard(ctx context.Context, userID string, card entities.Card) error {
	ret := _m.Called(ctx, userID, card)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entities.Card) error); ok {
		r0 = rf(ctx, userID, card)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CardUsecases_AddCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCard'
type CardUsecases_AddCard_Call struct {
	*mock.Call
}

// AddCard is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - card entities.Card
func (_e *CardUsecases_Expecter) AddCard(ctx interface{}, userID interface{}, card interface{}) *CardUsecases_AddCard_Call {
	return &CardUsecases_AddCard_Call{Call: _e.mock.On("AddCard", ctx, userID, card)}
}

func (_c *CardUsecases_AddCard_Call) Run(run func(ctx context.Context, userID string, card entities.Card)) *CardUsecases_AddCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(entities.Card))
	})
	return _c
}

func (_c *CardUsecases_AddCard_Call) Return(_a0 error) *CardUsecases_AddCard_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CardUsecases_AddCard_Call) RunAndReturn(run func(context.Context, string, entities.Card) error) *CardUsecases_AddCard_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCard provides a mock function with given fields: ctx, userID, meta
func (_m *CardUsecases) DeleteCard(ctx context.Context, userID string, meta string) error {
	ret := _m.Called(ctx, userID, meta)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, meta)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CardUsecases_DeleteCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCard'
type CardUsecases_DeleteCard_Call struct {
	*mock.Call
}

// DeleteCard is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - meta string
func (_e *CardUsecases_Expecter) DeleteCard(ctx interface{}, userID interface{}, meta interface{}) *CardUsecases_DeleteCard_Call {
	return &CardUsecases_DeleteCard_Call{Call: _e.mock.On("DeleteCard", ctx, userID, meta)}
}

func (_c *CardUsecases_DeleteCard_Call) Run(run func(ctx context.Context, userID string, meta string)) *CardUsecases_DeleteCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *CardUsecases_DeleteCard_Call) Return(_a0 error) *CardUsecases_DeleteCard_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CardUsecases_DeleteCard_Call) RunAndReturn(run func(context.Context, string, string) error) *CardUsecases_DeleteCard_Call {
	_c.Call.Return(run)
	return _c
}

// GetCard provides a mock function with given fields: ctx, userID, meta
func (_m *CardUsecases) GetCard(ctx context.Context, userID string, meta string) (entities.Card, error) {
	ret := _m.Called(ctx, userID, meta)

	var r0 entities.Card
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (entities.Card, error)); ok {
		return rf(ctx, userID, meta)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) entities.Card); ok {
		r0 = rf(ctx, userID, meta)
	} else {
		r0 = ret.Get(0).(entities.Card)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, meta)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CardUsecases_GetCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCard'
type CardUsecases_GetCard_Call struct {
	*mock.Call
}

// GetCard is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - meta string
func (_e *CardUsecases_Expecter) GetCard(ctx interface{}, userID interface{}, meta interface{}) *CardUsecases_GetCard_Call {
	return &CardUsecases_GetCard_Call{Call: _e.mock.On("GetCard", ctx, userID, meta)}
}

func (_c *CardUsecases_GetCard_Call) Run(run func(ctx context.Context, userID string, meta string)) *CardUsecases_GetCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *CardUsecases_GetCard_Call) Return(_a0 entities.Card, _a1 error) *CardUsecases_GetCard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CardUsecases_GetCard_Call) RunAndReturn(run func(context.Context, string, string) (entities.Card, error)) *CardUsecases_GetCard_Call {
	_c.Call.Return(run)
	return _c
}

// ListCard provides a mock function with given fields: ctx, userID
func (_m *CardUsecases) ListCard(ctx context.Context, userID string) ([]entities.Card, error) {
	ret := _m.Called(ctx, userID)

	var r0 []entities.Card
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]entities.Card, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []entities.Card); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Card)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CardUsecases_ListCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCard'
type CardUsecases_ListCard_Call struct {
	*mock.Call
}

// ListCard is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *CardUsecases_Expecter) ListCard(ctx interface{}, userID interface{}) *CardUsecases_ListCard_Call {
	return &CardUsecases_ListCard_Call{Call: _e.mock.On("ListCard", ctx, userID)}
}

func (_c *CardUsecases_ListCard_Call) Run(run func(ctx context.Context, userID string)) *CardUsecases_ListCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CardUsecases_ListCard_Call) Return(_a0 []entities.Card, _a1 error) *CardUsecases_ListCard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CardUsecases_ListCard_Call) RunAndReturn(run func(context.Context, string) ([]entities.Card, error)) *CardUsecases_ListCard_Call {
	_c.Call.Return(run)
	return _c
}

// NewCardUsecases creates a new instance of CardUsecases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCardUsecases(t interface {
	mock.TestingT
	Cleanup(func())
}) *CardUsecases {
	mock := &CardUsecases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
