// Code generated by mockery v2.23.4. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/Chystik/pass-man/internal/vault/card/entities"
	mock "github.com/stretchr/testify/mock"
)

// CardRepository is an autogenerated mock type for the CardRepository type
type CardRepository struct {
	mock.Mock
}

type CardRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CardRepository) EXPECT() *CardRepository_Expecter {
	return &CardRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userID, card
func (_m *CardRepository) Create(ctx context.Context, userID string, card entities.Card) error {
	ret := _m.Called(ctx, userID, card)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entities.Card) error); ok {
		r0 = rf(ctx, userID, card)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CardRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CardRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - card entities.Card
func (_e *CardRepository_Expecter) Create(ctx interface{}, userID interface{}, card interface{}) *CardRepository_Create_Call {
	return &CardRepository_Create_Call{Call: _e.mock.On("Create", ctx, userID, card)}
}

func (_c *CardRepository_Create_Call) Run(run func(ctx context.Context, userID string, card entities.Card)) *CardRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(entities.Card))
	})
	return _c
}

func (_c *CardRepository_Create_Call) Return(_a0 error) *CardRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CardRepository_Create_Call) RunAndReturn(run func(context.Context, string, entities.Card) error) *CardRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, meta
func (_m *CardRepository) Delete(ctx context.Context, userID string, meta string) error {
	ret := _m.Called(ctx, userID, meta)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, meta)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CardRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CardRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - meta string
func (_e *CardRepository_Expecter) Delete(ctx interface{}, userID interface{}, meta interface{}) *CardRepository_Delete_Call {
	return &CardRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, meta)}
}

func (_c *CardRepository_Delete_Call) Run(run func(ctx context.Context, userID string, meta string)) *CardRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *CardRepository_Delete_Call) Return(_a0 error) *CardRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CardRepository_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *CardRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetList provides a mock function with given fields: ctx, userID
func (_m *CardRepository) GetList(ctx context.Context, userID string) ([]entities.Card, error) {
	ret := _m.Called(ctx, userID)

	var r0 []entities.Card
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]entities.Card, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []entities.Card); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Card)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CardRepository_GetList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetList'
type CardRepository_GetList_Call struct {
	*mock.Call
}

// GetList is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *CardRepository_Expecter) GetList(ctx interface{}, userID interface{}) *CardRepository_GetList_Call {
	return &CardRepository_GetList_Call{Call: _e.mock.On("GetList", ctx, userID)}
}

func (_c *CardRepository_GetList_Call) Run(run func(ctx context.Context, userID string)) *CardRepository_GetList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CardRepository_GetList_Call) Return(_a0 []entities.Card, _a1 error) *CardRepository_GetList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CardRepository_GetList_Call) RunAndReturn(run func(context.Context, string) ([]entities.Card, error)) *CardRepository_GetList_Call {
	_c.Call.Return(run)
	return _c
}

// GetOne provides a mock function with given fields: ctx, userID, meta
func (_m *CardRepository) GetOne(ctx context.Context, userID string, meta string) (entities.Card, error) {
	ret := _m.Called(ctx, userID, meta)

	var r0 entities.Card
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (entities.Card, error)); ok {
		return rf(ctx, userID, meta)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) entities.Card); ok {
		r0 = rf(ctx, userID, meta)
	} else {
		r0 = ret.Get(0).(entities.Card)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, meta)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CardRepository_GetOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOne'
type CardRepository_GetOne_Call struct {
	*mock.Call
}

// GetOne is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - meta string
func (_e *CardRepository_Expecter) GetOne(ctx interface{}, userID interface{}, meta interface{}) *CardRepository_GetOne_Call {
	return &CardRepository_GetOne_Call{Call: _e.mock.On("GetOne", ctx, userID, meta)}
}

func (_c *CardRepository_GetOne_Call) Run(run func(ctx context.Context, userID string, meta string)) *CardRepository_GetOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *CardRepository_GetOne_Call) Return(_a0 entities.Card, _a1 error) *CardRepository_GetOne_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CardRepository_GetOne_Call) RunAndReturn(run func(context.Context, string, string) (entities.Card, error)) *CardRepository_GetOne_Call {
	_c.Call.Return(run)
	return _c
}

// NewCardRepository creates a new instance of CardRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCardRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CardRepository {
	mock := &CardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
