// Code generated by mockery v2.41.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	metadata "google.golang.org/grpc/metadata"

	pb "github.com/Chystik/pass-man/internal/infrastructure/grpc"
)

// FileService_DownloadClient is an autogenerated mock type for the FileService_DownloadClient type
type FileService_DownloadClient struct {
	mock.Mock
}

type FileService_DownloadClient_Expecter struct {
	mock *mock.Mock
}

func (_m *FileService_DownloadClient) EXPECT() *FileService_DownloadClient_Expecter {
	return &FileService_DownloadClient_Expecter{mock: &_m.Mock}
}

// CloseSend provides a mock function with given fields:
func (_m *FileService_DownloadClient) CloseSend() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CloseSend")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileService_DownloadClient_CloseSend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseSend'
type FileService_DownloadClient_CloseSend_Call struct {
	*mock.Call
}

// CloseSend is a helper method to define mock.On call
func (_e *FileService_DownloadClient_Expecter) CloseSend() *FileService_DownloadClient_CloseSend_Call {
	return &FileService_DownloadClient_CloseSend_Call{Call: _e.mock.On("CloseSend")}
}

func (_c *FileService_DownloadClient_CloseSend_Call) Run(run func()) *FileService_DownloadClient_CloseSend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FileService_DownloadClient_CloseSend_Call) Return(_a0 error) *FileService_DownloadClient_CloseSend_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileService_DownloadClient_CloseSend_Call) RunAndReturn(run func() error) *FileService_DownloadClient_CloseSend_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function with given fields:
func (_m *FileService_DownloadClient) Context() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// FileService_DownloadClient_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type FileService_DownloadClient_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *FileService_DownloadClient_Expecter) Context() *FileService_DownloadClient_Context_Call {
	return &FileService_DownloadClient_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *FileService_DownloadClient_Context_Call) Run(run func()) *FileService_DownloadClient_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FileService_DownloadClient_Context_Call) Return(_a0 context.Context) *FileService_DownloadClient_Context_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileService_DownloadClient_Context_Call) RunAndReturn(run func() context.Context) *FileService_DownloadClient_Context_Call {
	_c.Call.Return(run)
	return _c
}

// Header provides a mock function with given fields:
func (_m *FileService_DownloadClient) Header() (metadata.MD, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Header")
	}

	var r0 metadata.MD
	var r1 error
	if rf, ok := ret.Get(0).(func() (metadata.MD, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileService_DownloadClient_Header_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Header'
type FileService_DownloadClient_Header_Call struct {
	*mock.Call
}

// Header is a helper method to define mock.On call
func (_e *FileService_DownloadClient_Expecter) Header() *FileService_DownloadClient_Header_Call {
	return &FileService_DownloadClient_Header_Call{Call: _e.mock.On("Header")}
}

func (_c *FileService_DownloadClient_Header_Call) Run(run func()) *FileService_DownloadClient_Header_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FileService_DownloadClient_Header_Call) Return(_a0 metadata.MD, _a1 error) *FileService_DownloadClient_Header_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileService_DownloadClient_Header_Call) RunAndReturn(run func() (metadata.MD, error)) *FileService_DownloadClient_Header_Call {
	_c.Call.Return(run)
	return _c
}

// Recv provides a mock function with given fields:
func (_m *FileService_DownloadClient) Recv() (*pb.DownloadFileResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Recv")
	}

	var r0 *pb.DownloadFileResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (*pb.DownloadFileResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *pb.DownloadFileResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.DownloadFileResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileService_DownloadClient_Recv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recv'
type FileService_DownloadClient_Recv_Call struct {
	*mock.Call
}

// Recv is a helper method to define mock.On call
func (_e *FileService_DownloadClient_Expecter) Recv() *FileService_DownloadClient_Recv_Call {
	return &FileService_DownloadClient_Recv_Call{Call: _e.mock.On("Recv")}
}

func (_c *FileService_DownloadClient_Recv_Call) Run(run func()) *FileService_DownloadClient_Recv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FileService_DownloadClient_Recv_Call) Return(_a0 *pb.DownloadFileResponse, _a1 error) *FileService_DownloadClient_Recv_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileService_DownloadClient_Recv_Call) RunAndReturn(run func() (*pb.DownloadFileResponse, error)) *FileService_DownloadClient_Recv_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function with given fields: m
func (_m *FileService_DownloadClient) RecvMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileService_DownloadClient_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type FileService_DownloadClient_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *FileService_DownloadClient_Expecter) RecvMsg(m interface{}) *FileService_DownloadClient_RecvMsg_Call {
	return &FileService_DownloadClient_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *FileService_DownloadClient_RecvMsg_Call) Run(run func(m interface{})) *FileService_DownloadClient_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *FileService_DownloadClient_RecvMsg_Call) Return(_a0 error) *FileService_DownloadClient_RecvMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileService_DownloadClient_RecvMsg_Call) RunAndReturn(run func(interface{}) error) *FileService_DownloadClient_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function with given fields: m
func (_m *FileService_DownloadClient) SendMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileService_DownloadClient_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type FileService_DownloadClient_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *FileService_DownloadClient_Expecter) SendMsg(m interface{}) *FileService_DownloadClient_SendMsg_Call {
	return &FileService_DownloadClient_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *FileService_DownloadClient_SendMsg_Call) Run(run func(m interface{})) *FileService_DownloadClient_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *FileService_DownloadClient_SendMsg_Call) Return(_a0 error) *FileService_DownloadClient_SendMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileService_DownloadClient_SendMsg_Call) RunAndReturn(run func(interface{}) error) *FileService_DownloadClient_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Trailer provides a mock function with given fields:
func (_m *FileService_DownloadClient) Trailer() metadata.MD {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Trailer")
	}

	var r0 metadata.MD
	if rf, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}

	return r0
}

// FileService_DownloadClient_Trailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Trailer'
type FileService_DownloadClient_Trailer_Call struct {
	*mock.Call
}

// Trailer is a helper method to define mock.On call
func (_e *FileService_DownloadClient_Expecter) Trailer() *FileService_DownloadClient_Trailer_Call {
	return &FileService_DownloadClient_Trailer_Call{Call: _e.mock.On("Trailer")}
}

func (_c *FileService_DownloadClient_Trailer_Call) Run(run func()) *FileService_DownloadClient_Trailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FileService_DownloadClient_Trailer_Call) Return(_a0 metadata.MD) *FileService_DownloadClient_Trailer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileService_DownloadClient_Trailer_Call) RunAndReturn(run func() metadata.MD) *FileService_DownloadClient_Trailer_Call {
	_c.Call.Return(run)
	return _c
}

// NewFileService_DownloadClient creates a new instance of FileService_DownloadClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileService_DownloadClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileService_DownloadClient {
	mock := &FileService_DownloadClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
