// Code generated by mockery v2.41.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// isDownloadFileResponse_Data is an autogenerated mock type for the isDownloadFileResponse_Data type
type isDownloadFileResponse_Data struct {
	mock.Mock
}

type isDownloadFileResponse_Data_Expecter struct {
	mock *mock.Mock
}

func (_m *isDownloadFileResponse_Data) EXPECT() *isDownloadFileResponse_Data_Expecter {
	return &isDownloadFileResponse_Data_Expecter{mock: &_m.Mock}
}

// isDownloadFileResponse_Data provides a mock function with given fields:
func (_m *isDownloadFileResponse_Data) isDownloadFileResponse_Data() {
	_m.Called()
}

// isDownloadFileResponse_Data_isDownloadFileResponse_Data_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'isDownloadFileResponse_Data'
type isDownloadFileResponse_Data_isDownloadFileResponse_Data_Call struct {
	*mock.Call
}

// isDownloadFileResponse_Data is a helper method to define mock.On call
func (_e *isDownloadFileResponse_Data_Expecter) isDownloadFileResponse_Data() *isDownloadFileResponse_Data_isDownloadFileResponse_Data_Call {
	return &isDownloadFileResponse_Data_isDownloadFileResponse_Data_Call{Call: _e.mock.On("isDownloadFileResponse_Data")}
}

func (_c *isDownloadFileResponse_Data_isDownloadFileResponse_Data_Call) Run(run func()) *isDownloadFileResponse_Data_isDownloadFileResponse_Data_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *isDownloadFileResponse_Data_isDownloadFileResponse_Data_Call) Return() *isDownloadFileResponse_Data_isDownloadFileResponse_Data_Call {
	_c.Call.Return()
	return _c
}

func (_c *isDownloadFileResponse_Data_isDownloadFileResponse_Data_Call) RunAndReturn(run func()) *isDownloadFileResponse_Data_isDownloadFileResponse_Data_Call {
	_c.Call.Return(run)
	return _c
}

// newIsDownloadFileResponse_Data creates a new instance of isDownloadFileResponse_Data. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newIsDownloadFileResponse_Data(t interface {
	mock.TestingT
	Cleanup(func())
}) *isDownloadFileResponse_Data {
	mock := &isDownloadFileResponse_Data{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
